// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using propertyManagement.Data;

#nullable disable

namespace propertyManagement.Migrations
{
    [DbContext(typeof(PropertyManagementDbContext))]
    partial class PropertyManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeaseCharge", b =>
                {
                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.HasKey("ChargeId", "LeaseId")
                        .HasName("lease_charges_pkey");

                    b.HasIndex("LeaseId");

                    b.ToTable("lease_charges", (string)null);
                });

            modelBuilder.Entity("LeaseDocument", b =>
                {
                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.HasKey("LeaseId", "DocumentId")
                        .HasName("lease_documents_pkey");

                    b.HasIndex("DocumentId");

                    b.ToTable("lease_documents", (string)null);
                });

            modelBuilder.Entity("PropertyDocument", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.HasKey("PropertyId", "DocumentId")
                        .HasName("property_documents_pkey");

                    b.HasIndex("DocumentId");

                    b.ToTable("property_documents", (string)null);
                });

            modelBuilder.Entity("UserCharge", b =>
                {
                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ChargeId", "UserId")
                        .HasName("user_charges_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_charges", (string)null);
                });

            modelBuilder.Entity("UserDocument", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.HasKey("UserId", "DocumentId")
                        .HasName("user_documents_pkey");

                    b.HasIndex("DocumentId");

                    b.ToTable("user_documents", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("ChargeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("charge_type_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Desc")
                        .HasColumnType("text")
                        .HasColumnName("desc");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("charges_pkey");

                    b.HasIndex("ChargeTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("charges", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ChargePayment", b =>
                {
                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal?>("AmountApplied")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_applied");

                    b.HasKey("ChargeId", "PaymentId")
                        .HasName("charge_payments_pkey");

                    b.HasIndex("PaymentId");

                    b.ToTable("charge_payments", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ChargeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("charge_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "charge_statuses_name_key")
                        .IsUnique();

                    b.ToTable("charge_statuses", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ChargeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("charge_types_pkey");

                    b.HasIndex(new[] { "Name" }, "charge_types_name_key")
                        .IsUnique();

                    b.ToTable("charge_types", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("cities_pkey");

                    b.HasIndex("DistrictId");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ComplaintTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("complaint_type_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("complaints_pkey");

                    b.HasIndex("ComplaintTypeId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("complaints", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ComplaintPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("complaint_priorities_pkey");

                    b.HasIndex(new[] { "Name" }, "complaint_priorities_name_key")
                        .IsUnique();

                    b.ToTable("complaint_priorities", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ComplaintStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("complaint_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "complaint_statuses_name_key")
                        .IsUnique();

                    b.ToTable("complaint_statuses", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ComplaintType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("complaint_types_pkey");

                    b.HasIndex(new[] { "Name" }, "complaint_types_name_key")
                        .IsUnique();

                    b.ToTable("complaint_types", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("countries_pkey");

                    b.HasIndex(new[] { "Name" }, "countries_name_key")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("currencies_pkey");

                    b.HasIndex(new[] { "Code" }, "currencies_code_key")
                        .IsUnique();

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.HasKey("Id")
                        .HasName("districts_pkey");

                    b.HasIndex("StateId");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("document_type_id");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("document_url");

                    b.HasKey("Id")
                        .HasName("documents_pkey");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("document_types_pkey");

                    b.HasIndex(new[] { "Name" }, "document_types_name_key")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("LeaseTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("lease_type_id");

                    b.Property<decimal?>("MonthlyRent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_rent");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<decimal?>("SecurityDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("security_deposit");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UpfrontPayment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("upfront_payment");

                    b.HasKey("Id")
                        .HasName("leases_pkey");

                    b.HasIndex("LeaseTypeId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("leases", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.LeaseProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("LeaseTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("lease_type_id");

                    b.Property<decimal?>("MonthlyRent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_rent");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<decimal?>("SecurityDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("security_deposit");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UpfrontPayment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("upfront_payment");

                    b.HasKey("Id")
                        .HasName("lease_proposals_pkey");

                    b.HasIndex("LeaseTypeId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("lease_proposals", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.LeaseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("lease_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "lease_statuses_name_key")
                        .IsUnique();

                    b.ToTable("lease_statuses", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.LeaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("lease_types_pkey");

                    b.HasIndex(new[] { "Name" }, "lease_types_name_key")
                        .IsUnique();

                    b.ToTable("lease_types", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.OwnerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("gstin");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_name");

                    b.Property<int?>("OwnerTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type_id");

                    b.HasKey("UserId")
                        .HasName("owner_profiles_pkey");

                    b.HasIndex("OwnerTypeId");

                    b.ToTable("owner_profiles", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.OwnerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("owner_types_pkey");

                    b.HasIndex(new[] { "Name" }, "owner_types_name_key")
                        .IsUnique();

                    b.ToTable("owner_types", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaidBy")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("character varying")
                        .HasColumnName("transaction_ref");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PaidBy");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "TransactionRef" }, "payments_transaction_ref_key")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("payment_methods_pkey");

                    b.HasIndex(new[] { "Name" }, "payment_methods_name_key")
                        .IsUnique();

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "payment_statuses_name_key")
                        .IsUnique();

                    b.ToTable("payment_statuses", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ProfileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("profile_types_pkey");

                    b.HasIndex(new[] { "Name" }, "profile_types_name_key")
                        .IsUnique();

                    b.ToTable("profile_types", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_rent");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("SecurityDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("security_deposit");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("ThumbnailImgUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("thumbnail_img_url");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("UpfrontPayment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("upfront_payment");

                    b.HasKey("Id")
                        .HasName("properties_pkey");

                    b.HasIndex("CityId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusId");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.PropertyStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("property_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "property_statuses_name_key")
                        .IsUnique();

                    b.ToTable("property_statuses", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.ProposalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("proposal_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "proposal_statuses_name_key")
                        .IsUnique();

                    b.ToTable("proposal_statuses", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("states_pkey");

                    b.HasIndex("CountryId");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.TenantProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emergency_contact_number");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_income");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("occupation");

                    b.HasKey("UserId")
                        .HasName("tenant_profiles_pkey");

                    b.ToTable("tenant_profiles", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProfileTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("user_profiles_pkey");

                    b.HasIndex("ProfileTypeId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("propertyManagement.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_roles_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "user_roles_user_id_role_id_idx")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("LeaseCharge", b =>
                {
                    b.HasOne("propertyManagement.Models.Charge", null)
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .IsRequired()
                        .HasConstraintName("lease_charges_charge_id_fkey");

                    b.HasOne("propertyManagement.Models.Lease", null)
                        .WithMany()
                        .HasForeignKey("LeaseId")
                        .IsRequired()
                        .HasConstraintName("lease_charges_lease_id_fkey");
                });

            modelBuilder.Entity("LeaseDocument", b =>
                {
                    b.HasOne("propertyManagement.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .IsRequired()
                        .HasConstraintName("lease_documents_document_id_fkey");

                    b.HasOne("propertyManagement.Models.Lease", null)
                        .WithMany()
                        .HasForeignKey("LeaseId")
                        .IsRequired()
                        .HasConstraintName("lease_documents_lease_id_fkey");
                });

            modelBuilder.Entity("PropertyDocument", b =>
                {
                    b.HasOne("propertyManagement.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .IsRequired()
                        .HasConstraintName("property_documents_document_id_fkey");

                    b.HasOne("propertyManagement.Models.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("property_documents_property_id_fkey");
                });

            modelBuilder.Entity("UserCharge", b =>
                {
                    b.HasOne("propertyManagement.Models.Charge", null)
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .IsRequired()
                        .HasConstraintName("user_charges_charge_id_fkey");

                    b.HasOne("propertyManagement.Models.Lease", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_charges_user_id_fkey");
                });

            modelBuilder.Entity("UserDocument", b =>
                {
                    b.HasOne("propertyManagement.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .IsRequired()
                        .HasConstraintName("user_documents_document_id_fkey");

                    b.HasOne("propertyManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_documents_user_id_fkey");
                });

            modelBuilder.Entity("propertyManagement.Models.Charge", b =>
                {
                    b.HasOne("propertyManagement.Models.ChargeType", "ChargeType")
                        .WithMany("Charges")
                        .HasForeignKey("ChargeTypeId")
                        .HasConstraintName("charges_charge_type_id_fkey");

                    b.HasOne("propertyManagement.Models.ChargeStatus", "Status")
                        .WithMany("Charges")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("charges_status_id_fkey");

                    b.Navigation("ChargeType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("propertyManagement.Models.ChargePayment", b =>
                {
                    b.HasOne("propertyManagement.Models.Charge", "Charge")
                        .WithMany("ChargePayments")
                        .HasForeignKey("ChargeId")
                        .IsRequired()
                        .HasConstraintName("charge_payments_charge_id_fkey");

                    b.HasOne("propertyManagement.Models.Payment", "Payment")
                        .WithMany("ChargePayments")
                        .HasForeignKey("PaymentId")
                        .IsRequired()
                        .HasConstraintName("charge_payments_payment_id_fkey");

                    b.Navigation("Charge");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("propertyManagement.Models.City", b =>
                {
                    b.HasOne("propertyManagement.Models.District", "District")
                        .WithMany("Cities")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("cities_district_id_fkey");

                    b.Navigation("District");
                });

            modelBuilder.Entity("propertyManagement.Models.Complaint", b =>
                {
                    b.HasOne("propertyManagement.Models.ComplaintType", "ComplaintType")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintTypeId")
                        .HasConstraintName("complaints_complaint_type_id_fkey");

                    b.HasOne("propertyManagement.Models.ComplaintPriority", "Priority")
                        .WithMany("Complaints")
                        .HasForeignKey("PriorityId")
                        .HasConstraintName("complaints_priority_id_fkey");

                    b.HasOne("propertyManagement.Models.Property", "Property")
                        .WithMany("Complaints")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("complaints_property_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "ResolvedByNavigation")
                        .WithMany("ComplaintResolvedByNavigations")
                        .HasForeignKey("ResolvedBy")
                        .HasConstraintName("complaints_resolved_by_fkey");

                    b.HasOne("propertyManagement.Models.ComplaintStatus", "Status")
                        .WithMany("Complaints")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("complaints_status_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "Tenant")
                        .WithMany("ComplaintTenants")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("complaints_tenant_id_fkey");

                    b.Navigation("ComplaintType");

                    b.Navigation("Priority");

                    b.Navigation("Property");

                    b.Navigation("ResolvedByNavigation");

                    b.Navigation("Status");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("propertyManagement.Models.District", b =>
                {
                    b.HasOne("propertyManagement.Models.State", "State")
                        .WithMany("Districts")
                        .HasForeignKey("StateId")
                        .HasConstraintName("districts_state_id_fkey");

                    b.Navigation("State");
                });

            modelBuilder.Entity("propertyManagement.Models.Document", b =>
                {
                    b.HasOne("propertyManagement.Models.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("documents_document_type_id_fkey");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("propertyManagement.Models.Lease", b =>
                {
                    b.HasOne("propertyManagement.Models.LeaseType", "LeaseType")
                        .WithMany("Leases")
                        .HasForeignKey("LeaseTypeId")
                        .HasConstraintName("leases_lease_type_id_fkey");

                    b.HasOne("propertyManagement.Models.Property", "PropertyNavigation")
                        .WithMany("Leases")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("leases_property_id_fkey");

                    b.HasOne("propertyManagement.Models.LeaseProposal", "Proposal")
                        .WithMany("Leases")
                        .HasForeignKey("ProposalId")
                        .HasConstraintName("leases_proposal_id_fkey");

                    b.HasOne("propertyManagement.Models.LeaseStatus", "Status")
                        .WithMany("Leases")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("leases_status_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("leases_tenant_id_fkey");

                    b.Navigation("LeaseType");

                    b.Navigation("PropertyNavigation");

                    b.Navigation("Proposal");

                    b.Navigation("Status");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("propertyManagement.Models.LeaseProposal", b =>
                {
                    b.HasOne("propertyManagement.Models.LeaseType", "LeaseType")
                        .WithMany("LeaseProposals")
                        .HasForeignKey("LeaseTypeId")
                        .HasConstraintName("lease_proposals_lease_type_id_fkey");

                    b.HasOne("propertyManagement.Models.Property", "Property")
                        .WithMany("LeaseProposals")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("lease_proposals_property_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "ReviewedByNavigation")
                        .WithMany("LeaseProposalReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("lease_proposals_reviewed_by_fkey");

                    b.HasOne("propertyManagement.Models.ProposalStatus", "Status")
                        .WithMany("LeaseProposals")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("lease_proposals_status_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "Tenant")
                        .WithMany("LeaseProposalTenants")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("lease_proposals_tenant_id_fkey");

                    b.Navigation("LeaseType");

                    b.Navigation("Property");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Status");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("propertyManagement.Models.OwnerProfile", b =>
                {
                    b.HasOne("propertyManagement.Models.OwnerType", "OwnerType")
                        .WithMany("OwnerProfiles")
                        .HasForeignKey("OwnerTypeId")
                        .HasConstraintName("owner_profiles_owner_type_id_fkey");

                    b.HasOne("propertyManagement.Models.UserProfile", "User")
                        .WithOne("OwnerProfile")
                        .HasForeignKey("propertyManagement.Models.OwnerProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("owner_profiles_user_id_fkey");

                    b.Navigation("OwnerType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("propertyManagement.Models.Payment", b =>
                {
                    b.HasOne("propertyManagement.Models.Currency", "Currency")
                        .WithMany("Payments")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("payments_currency_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "PaidByNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("PaidBy")
                        .HasConstraintName("payments_paid_by_fkey");

                    b.HasOne("propertyManagement.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .HasConstraintName("payments_payment_method_id_fkey");

                    b.HasOne("propertyManagement.Models.PaymentStatus", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("payments_status_id_fkey");

                    b.Navigation("Currency");

                    b.Navigation("PaidByNavigation");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("propertyManagement.Models.Property", b =>
                {
                    b.HasOne("propertyManagement.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .HasConstraintName("properties_city_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("properties_owner_id_fkey");

                    b.HasOne("propertyManagement.Models.PropertyStatus", "Status")
                        .WithMany("Properties")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("properties_status_id_fkey");

                    b.Navigation("City");

                    b.Navigation("Owner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("propertyManagement.Models.State", b =>
                {
                    b.HasOne("propertyManagement.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("states_country_id_fkey");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("propertyManagement.Models.TenantProfile", b =>
                {
                    b.HasOne("propertyManagement.Models.UserProfile", "User")
                        .WithOne("TenantProfile")
                        .HasForeignKey("propertyManagement.Models.TenantProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("tenant_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("propertyManagement.Models.UserProfile", b =>
                {
                    b.HasOne("propertyManagement.Models.ProfileType", "ProfileType")
                        .WithMany("UserProfiles")
                        .HasForeignKey("ProfileTypeId")
                        .IsRequired()
                        .HasConstraintName("user_profiles_profile_type_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("propertyManagement.Models.UserProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("user_profiles_user_id_fkey");

                    b.Navigation("ProfileType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("propertyManagement.Models.UserRole", b =>
                {
                    b.HasOne("propertyManagement.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("propertyManagement.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("propertyManagement.Models.Charge", b =>
                {
                    b.Navigation("ChargePayments");
                });

            modelBuilder.Entity("propertyManagement.Models.ChargeStatus", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("propertyManagement.Models.ChargeType", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("propertyManagement.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("propertyManagement.Models.ComplaintPriority", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("propertyManagement.Models.ComplaintStatus", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("propertyManagement.Models.ComplaintType", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("propertyManagement.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("propertyManagement.Models.Currency", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("propertyManagement.Models.District", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("propertyManagement.Models.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("propertyManagement.Models.LeaseProposal", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("propertyManagement.Models.LeaseStatus", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("propertyManagement.Models.LeaseType", b =>
                {
                    b.Navigation("LeaseProposals");

                    b.Navigation("Leases");
                });

            modelBuilder.Entity("propertyManagement.Models.OwnerType", b =>
                {
                    b.Navigation("OwnerProfiles");
                });

            modelBuilder.Entity("propertyManagement.Models.Payment", b =>
                {
                    b.Navigation("ChargePayments");
                });

            modelBuilder.Entity("propertyManagement.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("propertyManagement.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("propertyManagement.Models.ProfileType", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("propertyManagement.Models.Property", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("LeaseProposals");

                    b.Navigation("Leases");
                });

            modelBuilder.Entity("propertyManagement.Models.PropertyStatus", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("propertyManagement.Models.ProposalStatus", b =>
                {
                    b.Navigation("LeaseProposals");
                });

            modelBuilder.Entity("propertyManagement.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("propertyManagement.Models.State", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("propertyManagement.Models.User", b =>
                {
                    b.Navigation("ComplaintResolvedByNavigations");

                    b.Navigation("ComplaintTenants");

                    b.Navigation("LeaseProposalReviewedByNavigations");

                    b.Navigation("LeaseProposalTenants");

                    b.Navigation("Leases");

                    b.Navigation("Payments");

                    b.Navigation("Properties");

                    b.Navigation("UserProfile");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("propertyManagement.Models.UserProfile", b =>
                {
                    b.Navigation("OwnerProfile");

                    b.Navigation("TenantProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
